### PR TITLE
Don't collect security groups in rhev refresh

### PR DESCRIPTION
**Pull request by agrare**
Wanted to get the conversation started here with @borod108 and @aufi
Is this an appropriate solution for both ovirt and openstack?

@borod108 I'd like to add a rhv version check, something like:

```
def security_groups
  manager.api_version > 4.2.6 && manager.api_version < 4.3 ? [] : super
end
```

Can you help with the correct versions to check for there?

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1649886

### CODE REVIEW

**Comment by agrare** [comment]
@borod108 so the only api_version I see from that manager is `"v2"` at least in the specs, and the parent_manager.api_version is nil (again at least in the specs)

**Comment by borod108** [comment]
@agrare so we need to fetch the rhv manager and do something like:
https://github.com/ManageIQ/manageiq-providers-ovirt/blob/master/app/models/manageiq/providers/redhat/infra_manager/provision/configuration.rb#L18

The v2 is probably for neutron not for rhv.

This is an example of why I do not like this solution: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/309/files
When openstack repo updates, the provider tests do not run, and it could just be broken without anyone  knowing it :(

**Comment by aufi** [comment]
From OpenStack point of view, this PR is okay (doesn't affect OSP provider). We (me, @mansam, @Ladas ) discussed that other solution could be making security groups in refresh optional for both OSP and ovirt.

**Comment by agrare** [comment]
> @agrare so we need to fetch the rhv manager and do something like:
https://github.com/ManageIQ/manageiq-providers-ovirt/blob/master/app/models/manageiq/providers/redhat/infra_manager/provision/configuration.rb#L18

@borod108 cool that's exactly what I was planning on doing, in the spec I was looking at that api_version was `nil` which is why I asked but that might just be an issue with the spec setup.

> The v2 is probably for neutron not for rhv.

And we can't tell from the neutron version if this will work or not?  It seems like it should given that the error is in neutron I think (@aufi ?)

> This is an example of why I do not like this solution: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/309/files
> When openstack repo updates, the provider tests do not run, and it could just be broken without anyone knowing it :(

This was the most minimal change I could think of making, these things will happen periodically with any inter-package dependencies and we run travis every night regardless of if a commit was made so we should know within a day of any such breakages.

If it is going multiple days/weeks without being noticed that sounds like a different issue (that no one is looking at travis for this repo).  That should be part of the normal day's workflow for any repo maintainer.

Also @aufi I'd say your team should be cognisant of the ovirt neutron dependency and manually test ovirt refresh when doing any changes to the openstack network_manager refresh as much as possible.  Obviously things will fall through the cracks but if we try to be better then we can catch probably 90% of these issues.

**Comment by aufi** [comment]
> > @agrare so we need to fetch the rhv manager and do something like:
> > https://github.com/ManageIQ/manageiq-providers-ovirt/blob/master/app/models/manageiq/providers/redhat/infra_manager/provision/configuration.rb#L18
> 
> @borod108 cool that's exactly what I was planning on doing, in the spec I was looking at that api_version was `nil` which is why I asked but that might just be an issue with the spec setup.
> 
> > The v2 is probably for neutron not for rhv.
> 
> And we can't tell from the neutron version if this will work or not? It seems like it should given that the error is in neutron I think (@aufi ?)

Yes, that's Neutron API version which is not closely related to oVirt version. I think the condition for versions based on API version is not helpful in this case.

**Comment by aufi** [comment]
> > This is an example of why I do not like this solution: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/309/files
> > When openstack repo updates, the provider tests do not run, and it could just be broken without anyone knowing it :(
> 
> This was the most minimal change I could think of making, these things will happen periodically with any inter-package dependencies and we run travis every night regardless of if a commit was made so we should know within a day of any such breakages.
> 

That would be great :+1: 

> If it is going multiple days/weeks without being noticed that sounds like a different issue (that no one is looking at travis for this repo). That should be part of the normal day's workflow for any repo maintainer.
> 
> Also @aufi I'd say your team should be cognisant of the ovirt neutron dependency and manually test ovirt refresh when doing any changes to the openstack network_manager refresh as much as possible. Obviously things will fall through the cracks but if we try to be better then we can catch probably 90% of these issues.

The "dependency" is unfortunately not well defined, we noticed that the code is reused just when OpenStack changes started failing in oVirt side. We can think about Network-related issues before merging network-related changes in OpenStack provider. But I don't think we should run inventory tests against oVirt/RHV environment on OpenStack provider side. Nightly test runs of oVirt provider sounds reasonable to. It should help identify errors quickly and help us (OSP) understand what changes need to be considered as risky for oVirt.

**Comment by agrare** [comment]
> The "dependency" is unfortunately not well defined, we noticed that the code is reused just when OpenStack changes started failing in oVirt provider.

Right, that sounds pretty well defined though no?  They inherit from the OpenStack NetworkManager so e.g. any change that requires you to update specs or VCRs for the NetworkManager would also impact the Ovirt provider.

**Comment by agrare** [comment]
@borod108 I figured out why api_version was nil, just needed to reload `@ems` in a spec test so we should be good to go now, please take a look

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 1505664d43400aebf055584c8ecdc061331c1144
Author: Boris Od <bodnopoz@redhat.com>
Date:   Fri May 17 05:36:04 2019 +0300

    Merge pull request #365 from agrare/bz_1649886_dont_collect_security_groups
    
    Don't collect security groups in rhev refresh
    
    (cherry picked from commit a86dcf2019dab2792c116de7c092810d0d2cf9ab)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1669023
```

**Pull request merged**
