### PR TITLE
[HAMMER] Update i18n catalog for hammer

### PR DESCRIPTION
**Pull request by mzazrivec**

### CODE REVIEW

**Comment by simaishi** [comment]
Travis failure:

```
  1) placeholders gettext strings do not contain interpolations
     Failure/Error: expect(errors).to be_empty
       expected `["\"Memory Limit is supported for RHV 4.1 and above. Current provider version is \#{ems.api_version}.\""].empty?` to return true, got false
     Shared Example Group: :placeholders called from ./spec/i18n/placeholders_spec.rb:2
     # ./spec/manageiq/spec/shared/i18n/placeholders.rb:49:in `block (2 levels) in <top (required)>'
```

**Comment by pkliczewski** [comment]
@simaishi I asked @borod108 to take a look. Maybe we are missing a backport.

**Comment by mzazrivec** [comment]
CI fix: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/297

**Comment by pkliczewski** [comment]
@borod108 Please take a look at the build failure.

**Pull request merged**
