### PR TITLE
Add applications requests to VCRs

### PR DESCRIPTION
**Pull request by gekorob**
For each vm there will be a request to get applications.
This PR add mock requests to VCRs, returning empty applications section, as a temporary fix to specs failing

### CODE REVIEW

**Comment by gekorob** [comment]
@agrare @djberg96  added the label 'technical debt' and 'test' just because it's a temporary fix

**Comment by agrare** [comment]
Thanks @gekorob !  @djberg96 can you test your PR with this applied?

**Comment by gekorob** [comment]
@djberg96 just rember to change 'tools_status' in 
*spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb*
for the vm  assertions only (because if I'm not wrong you are not going to ask applications for templates, am I right?).

**Comment by djberg96** [comment]
@gekorob I'm ultimately making this call: `connection.follow_link(vm.applications)`. Full changes here: https://github.com/ManageIQ/manageiq-providers-ovirt/pull/504/files.

**Comment by gekorob** [comment]
@djberg96 yes, so it should be enough to change tools_status in the two assertion methods about vm.

https://github.com/ManageIQ/manageiq-providers-ovirt/blob/5aaa3a7d8c61741185616f3f0d932edf9a788fc6/spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb#L435

https://github.com/ManageIQ/manageiq-providers-ovirt/blob/5aaa3a7d8c61741185616f3f0d932edf9a788fc6/spec/models/manageiq/providers/redhat/infra_manager/refresher/refresher_4_async_graph_spec.rb#L580

**Comment by djberg96** [comment]
@gekorob, @agrare Yep, with this PR and the updates to the specs, the specs for https://github.com/ManageIQ/manageiq-providers-ovirt/pull/505 pass.

**Comment by simaishi** [comment]
@gekorob @agrare can this be `jansa/yes` and `ivanchuk/yes`?

**Comment by agrare** [comment]
Yes, labeled

**Comment by simaishi** [comment]
@gekorob Travis is red in jansa. Can you please take a look?
https://travis-ci.com/github/ManageIQ/manageiq-providers-ovirt/jobs/378021402

```
Failures:
  1) ManageIQ::Providers::Redhat::InfraManager::Refresher will perform a full refresh
     Failure/Error: raise "connection_vcr could not find a response for: #{req_key}"
     RuntimeError:
       connection_vcr could not find a response for: https://engine-43.lab.inz.redhat.com:443/ovirt-engine/api/vms/ca7e8d64-0fc7-45de-b258-ae471ea31056/applications{}GET
     # ./spec/support/ovirt_sdk/connection_vcr.rb:32:in `wait'
```

**Comment by gekorob** [comment]
@simaishi I'm looking into that

**Comment by simaishi** [comment]
@gekorob Backporting this PR to ivanchuk branch conflicts. Can you please create a separate PR for ivanchuk?

**Comment by gekorob** [comment]
Hi @simaishi, sure I'll try to work on that today or tomorrow

**Comment by simaishi** [comment]
@gekorob Thank you. We have a build scheduled next Tuesday. Please let me know if you think you'll need more time.

**Comment by simaishi** [comment]
@gekorob Travis looks good on #520 Thank you!!

**Comment by simaishi** [comment]
Backported to ivanchuk via https://github.com/ManageIQ/manageiq-providers-ovirt/pull/520

**Pull request merged**
