### PR TITLE
Update client to use renamed NetworkDiscovery

### PR DESCRIPTION
**Pull request by jrafanie**
https://github.com/ManageIQ/manageiq/pull/16994

### CODE REVIEW

**Comment by mwperina** [comment]
@masayag @borod108

**Comment by borod108** [comment]
@mwperina this is using the v3, but we talked about it not being urgent to change it to v4.

**Comment by gildub** [comment]
@jrafanie, the `require` needs update too. 
https://github.com/ManageIQ/manageiq-providers-ovirt/pull/209 takes care of it.
Thanks

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit ce03120e1560ad6bd49958f62d7e8c26fbee3ceb
Author: Boris Od <boris.od@gmail.com>
Date:   Wed Feb 14 17:33:12 2018 +0200

    Merge pull request #208 from jrafanie/rename_manageiq_network_to_network_discovery
    
    Update client to use renamed NetworkDiscovery
    (cherry picked from commit edfaaa8732f451e95414639538ee8a8afbf99a83)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1552665
```

**Pull request merged**
