### PR TITLE
Credential verification errors for new provider

### PR DESCRIPTION
**Pull request by borod108**
The way to handle errors raised from credentials verification for a new
provider and an existing providers was diffrent, which caused diffrent
error messages to be displayed.

This fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1519815

### CODE REVIEW

**Comment by borod108** [comment]
@miq-bot add_label gaprindashvili/yes

@masayag @jhernand can you take a look?

**Comment by borod108** [comment]
[credential validation errors for new provider](https://trello.com/c/YQ4TpI7j/288-credential-validation-errors-for-new-provider)

**Comment by masayag** [comment]
@miq-bot add_label bug

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 361e1ad3723bd9f5b31df0edb90e2a885c4d9e27
Author: Moti Asayag <masayag@redhat.com>
Date:   Tue Jan 9 12:31:28 2018 +0200

    Merge pull request #188 from borod108/bugs/verify_cred_exceptions
    
    Credential verification errors for new provider
    (cherry picked from commit 92a547bb9267d3d2a13f4631df70877d756b3f7b)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1519815
```

**Pull request merged**
