### PR TITLE
Add cpu type and speed to vm hardware info

### PR DESCRIPTION
**Pull request by djberg96**
Attempting to add cpu type and speed to the vm hardware for the Ovirt provider.

Draft for now since the information appears to always be empty.

### CODE REVIEW

**Comment by djberg96** [comment]
Using the SDK directly, I'm seeing stuff like this as a response for a vm.cpu:

```
#<OvirtSDK4::Cpu:0x00007fe8d8025b70
  @href=nil,
  @architecture="x86_64",
  @cores=nil,
  @cpu_tune=nil,
  @level=nil,
  @mode=nil,
  @name=nil,
  @speed=nil,
  @topology=#<OvirtSDK4::CpuTopology:0x00007fe8d80257d8 @href=nil, @cores=2, @sockets=2, @threads=1>, @type=nil>
```
Why are most fields blank? Is this is an issue with the SDK? Or does the raw response not include this information? Still digging.

**Comment by gekorob** [comment]
Hi @djberg96, as far as I know the speed and type parameters for the cpu object are populated for the host
```
host = conn.follow_link(vm.host)
host.cpu

#<OvirtSDK4::Cpu:0x0000000001b5ad00 
@href=nil, 
@architecture=nil, 
@cores=nil, @cpu_tune=nil, @level=nil, @mode=nil, 
@name="Intel Xeon Processor (Skylake)", 
@speed=2100.0, 
@topology=#<OvirtSDK4::CpuTopology:0x0000000001b59798 @href=nil, 
@cores=4, @sockets=1, @threads=1>, 
@type="Intel Skylake Server IBRS SSBD Family">
```

**Comment by djberg96** [comment]
@gekorob Makes sense, if it's a guest VM on a host, it won't have its own cpu information.

Alright, I may tinker with overloading the vm.rb file accessors instead.

**Comment by gekorob** [comment]
@djberg96 Thanks for the effort, in case you need anything, just ask

**Comment by djberg96** [comment]
BZ was closed, so closing this. The CPU information displayed in the RHV UI comes from the host or the cluster, though even then it's just the family.

**Pull request closed without merging**
