### PR TITLE
Add spec for target new_refresh

### PR DESCRIPTION
**Pull request by borod108**
Spec to check that after refreshing new target template vm.ems_cluster is not
nil.

### CODE REVIEW

**Comment by borod108** [comment]
@masayag can we merge?

**Comment by borod108** [comment]
@miq-bot add_label gaprindashvili/yes

I think this spec should be backported.

**Comment by masayag** [comment]
> @masayag can we merge?

Please update the target_hash to reflect its role, the current name is too generic, assuming we'd like to add additional yml files for other targeted refresh scenarios.

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit b9bd0f161e28fc46742a84bb068f53fbd6b2ab47
Author: Moti Asayag <masayag@redhat.com>
Date:   Sun Jan 7 19:56:36 2018 +0200

    Merge pull request #185 from borod108/spec/publish_vm
    
    Add spec for target new_refresh
    (cherry picked from commit c7466d09e6cf4e6791c9c3e68e3aa0878a49bef9)
```

**Pull request merged**
