### PR TITLE
Provide missing events

### PR DESCRIPTION
**Pull request by pkliczewski**
oVirt generates many kinds of events which are not defined on the provider side.
This PR provides missing events.

Fixes: https://bugzilla.redhat.com/1509004

### CODE REVIEW

**Comment by pkliczewski** [comment]
@miq-bot assign @masayag

**Comment by pkliczewski** [comment]
@borod108 please review

**Comment by pkliczewski** [comment]
[Bug 1509004 - rhv41 provider: event with event_type = "UNKNOWN" appears event_streams table when restart guest is called for vm](https://trello.com/c/gVqE7VVT/282-bug-1509004-rhv41-provider-event-with-eventtype-unknown-appears-eventstreams-table-when-restart-guest-is-called-for-vm)

**Comment by pkliczewski** [comment]
@miq-bot add_labels gaprindashvili/yes

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 4e1157af902f3b8af2962e6c51f6c91f8c2945fd
Author: Moti Asayag <masayag@redhat.com>
Date:   Wed Dec 20 13:12:22 2017 +0200

    Merge pull request #180 from pkliczewski/events
    
    Provide missing events
    (cherry picked from commit ec2d09b11d20a7d898a30f7a34496a30326a52e0)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1530742
```

**Pull request merged**
