### PR TITLE
Code style cleanup

### PR DESCRIPTION
**Pull request by gekorob**
Some cleanup in yaml and specs

### CODE REVIEW

**Comment by gekorob** [comment]
@miq-bot add_label cleanup

**Comment by borod108** [comment]
@gekorob I think that auto generated ymls should not be cleaned up - or we shuold change the code that generates them.
Also - if it is a cleanup I think it makes sense to cleanup the rubocops messages:)

**Comment by gekorob** [comment]
@borod108, Agree with you, I'll bring back ymls at the original form and fix the missing messages. Unfortunately I'm not able to run rubocop in local due to some configuration outdated.
I'll put wip label until I'll finish the process

**Comment by gekorob** [comment]
@miq-bot add_label wip

**Comment by gekorob** [comment]
@miq-bot remove_label wip

**Pull request merged**
