### PR TITLE
Preload disks during refresh for optimisation

### PR DESCRIPTION
**Pull request by borod108**
Preload disks during refresh for optimisation

### CODE REVIEW

**Comment by borod108** [comment]
@pkliczewski the tests that fail seem to be related to the graph refresh, they do not fail for me in local fetched env. Maybe you have an idea?
@masayag can you please review?

**Comment by pkliczewski** [comment]
@borod108 The tests are failing because we are missing the last PR. Your env have to use stale manageiq repo so you do not see the issue.

**Comment by pkliczewski** [comment]
@borod108 Could you please update graph refresh code as well?

**Comment by borod108** [comment]
@pkliczewski I added the code to the graph refresh, please review

**Comment by borod108** [comment]
@miq-bot remove lable wip

**Comment by borod108** [comment]
@miq-bot remove label wip

@miq-bot assign @oourfali

**Comment by masayag** [comment]
@miq-bot remove_label wip

**Pull request merged**
