### PR TITLE
Excluding archived vms from reconfigurable? method.

### PR DESCRIPTION
**Pull request by pkomanek**
As a result of request from related BZ below we are excluding archived vms from being able to be reconfigurable. Similar change is being made in 1 more repository(https://github.com/ManageIQ/manageiq-providers-vmware/pull/467).

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1743533

### CODE REVIEW

**Comment by gekorob** [comment]
BTW I can see now that it's the same change required in
https://github.com/ManageIQ/manageiq-providers-vmware/pull/467
Let me know

**Comment by gekorob** [comment]
@agrare LGTM but there's a spec failing. If you want I can merge and fix the spec with another PR

**Comment by agrare** [comment]
Yeah that's the same failure as the vmware repo, @pkomanek can you fix that spec here as well?

**Comment by gekorob** [comment]
@agrare @pkomanek let me know if I can help

**Comment by gekorob** [comment]
@pkomanek great thanks

**Comment by gekorob** [comment]
@borod108 @agrare should it be ivanchuk/yes?

**Comment by gekorob** [comment]
@miq-bot add_label bug, ivanchuk/yes

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 51dcc48f3d752539f135ba349475acc41d71820e
Author: Roberto Ciatti <gekorob@users.noreply.github.com>
Date:   Tue Nov 19 13:03:40 2019 +0100

    Merge pull request #421 from pkomanek/bz_1743533_exclude_archived_vms_from_reconfigurable

    Excluding archived vms from reconfigurable? method.

    (cherry picked from commit 973c51d4d60c47d14ec4dd9b8822fffdadb89482)

    https://bugzilla.redhat.com/show_bug.cgi?id=1743533
```

**Pull request merged**
