### PR TITLE
External network registrations fix

### PR DESCRIPTION
**Pull request by gekorob**
Due to a change in the openstack provider, this commit fix the VCR
registrations to let external network specs work again.

### CODE REVIEW

**Comment by borod108** [comment]
@gekorob hi, do you want to merge this?
Is this working with a real env with rhv 4.3.6?

**Comment by gekorob** [comment]
@borod108 it's a simple fix only to let test passing in case there are no security-group rules. I don't have a real env with an external network configured with openstack or other.

**Comment by gekorob** [comment]
@miq-bot add_label wip

**Comment by gekorob** [comment]
@miq-bot remove_label wip

**Comment by simaishi** [comment]
@gekorob Travis is failing in hammer branch (soon ivanchuk as well), but cherry-pick'ing this PR conflicts. Can you please create PRs for hammer and ivanchuk?

**Pull request merged**
