### PR TITLE
Support host maintenance actions

### PR DESCRIPTION
**Pull request by masayag**
The patch adds support for host maintenance actions (activate
and deactivate host) to the host power operations.

### CODE REVIEW

**Comment by masayag** [comment]
Need to verify the maintenance and maintenance_reason necessity to the flow or as a result of fetching any of the maintenance related events (VDS_ACTIVATE_FAILED / VDS_MAINTENANCE_FAILED / USER_VDS_MAINTENANCE / USER_VDS_MAINTENANCE_WITHOUT_REASON )

**Comment by borod108** [comment]
But fix tests...

**Comment by borod108** [comment]
@masayag please add specs in future PR

**Comment by borod108** [comment]
@miq-bot assign @oourfali

**Comment by masayag** [comment]
Support for v3 will be enabled once https://github.com/ManageIQ/ovirt/pull/84 is merged.

**Pull request merged**
