### PR TITLE
[IVANCHUK] Remodel to add networks by external providers

### PR DESCRIPTION
**Pull request by borod108**
Remodel the networking to add the vnic profiles related to networks that
are managed by external providers to the provisioning network dialog.

Backport of https://github.com/ManageIQ/manageiq-providers-ovirt/pull/450

Related to: https://bugzilla.redhat.com/show_bug.cgi?id=1767787

### CODE REVIEW

**Comment by agrare** [comment]
Hey @borod108 I think the changes to the ovirt_services file [here](https://github.com/ManageIQ/manageiq-providers-ovirt/commit/62b1a8409fed8d93e182963c8ec41b206d35e66f#diff-6c359b28e3fa0f7e669d3797af1f0fed) should go to `ovirt_services/strategies/v4.rb` on ivanchuk

**Comment by dmetzger57** [comment]
@borod108 @agrare just a heads up, the associated BZ is now being considered a blocker for Monday's (Jan-13) build.

**Comment by borod108** [comment]
@agrare hah, oops. Well it still works, but now it is even better because we have all the code in two places so we won't loose it :p

**Comment by agrare** [comment]
@simaishi https://github.com/ManageIQ/manageiq-providers-ovirt/pull/457 should be backported with this

**Comment by simaishi** [comment]
> @simaishi #457 should be backported with this

@agrare thanks, done.

**Pull request merged**
