### PR TITLE
Fix rescue during PXE and ISO provisioning

### PR DESCRIPTION
**Pull request by borod108**
This fixes https://bugzilla.redhat.com/show_bug.cgi?id=1446409

### CODE REVIEW

**Comment by borod108** [comment]
@miq-bot add-label wip

**Comment by borod108** [comment]
@miq-bot remove-label wip
@miq-bot add-label fine/yes
@miq-bot add-label bug/blocker

@masayag please review

**Comment by borod108** [comment]
@miq-bot add-label wip

**Comment by borod108** [comment]
@miq-bot remove-label wip

**Comment by borod108** [comment]
@durandom hi this is a blocker, please take a look.

**Comment by blomquisg** [comment]
This looks like something that could use a test.

**Comment by durandom** [comment]
@borod108 do you want to add a short test for `powered_on_in_provider?` ?

**Comment by borod108** [comment]
@durandom added a spec that would have caught the bug, as for the the method in ovirt_services, I am working on getting as much coverage there as possible but it will take some time.
Is this good enough to merge?

**Comment by simaishi** [comment]
Fine backport (to manageiq repo) details:

```
$ git log -1
commit 8e5b51da23db7e54b48fb6d3e5025b9b3bfa3490
Author: Marcel Hild <hild@b4mad.net>
Date:   Tue May 2 15:48:37 2017 +0200

    Merge pull request #24 from borod108/bugs/1446409pxe_prov
    
    Fix rescue during PXE and ISO provisioning
    (cherry picked from commit 729b410359f3e80af7f7323296e7e02828688b5d)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1447382
```

**Pull request merged**
