### PR TITLE
Performance improvements for graph refresh

### PR DESCRIPTION
**Pull request by borod108**
Added spec for scale.
Add a fix for custom saving block (suggested by Ladas)

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1566468

### CODE REVIEW

**Comment by borod108** [comment]
@pkliczewski @masayag please review

**Comment by simaishi** [comment]
@borod108 @pkliczewski Can this be `gaprindashvili/yes`? The BZ is marked as blocker for the next gaprindashvili release.

**Comment by borod108** [comment]
@simaishi yes, also added https://github.com/ManageIQ/manageiq-providers-ovirt/pull/240 because it is also required for the fix. (Commented on BZ as well)

**Comment by simaishi** [comment]
@borod108 @agrare Travis is failing in Gaprindashvili branch, can you please take a look?  FYI, I backported this PR and https://github.com/ManageIQ/manageiq-providers-ovirt/pull/240 together.

https://travis-ci.org/ManageIQ/manageiq-providers-ovirt/builds/379858464

**Comment by agrare** [comment]
@simaishi looks like https://github.com/ManageIQ/manageiq-providers-ovirt/pull/237 is depending on some changes to `ConnectionVcr`, this passes if I backport https://github.com/ManageIQ/manageiq-providers-ovirt/pull/183 and https://github.com/ManageIQ/manageiq-providers-ovirt/pull/220

**Comment by agrare** [comment]
Which causes other spec failures... @borod108 can you look at https://travis-ci.org/ManageIQ/manageiq-providers-ovirt/jobs/380197849#L1982 ?

**Pull request merged**
