### PR TITLE
[HAMMER] Add security group rules requests to registrations

### PR DESCRIPTION
**Pull request by gekorob**
Added security group rules sections to the vcr registration to fix broken hammer tests.

### CODE REVIEW

**Comment by gekorob** [comment]
@miq-bot add_label wip

**Comment by gekorob** [comment]
@miq-bot remove_label wip

**Comment by gekorob** [comment]
@agrare I made changes before knowing of that PR... I'll remove my changes and backport the PR#385

**Comment by gekorob** [comment]
No new releases expected for 5.10 in the near future. We'll reopen this one in case needed

**Comment by simaishi** [comment]
Re-opening to get hammer back to green...

**Comment by simaishi** [comment]
@gekorob @agrare will you be able to update the PR to fix the 2 remaining tests? Looks like the IP address changed.

https://travis-ci.com/github/ManageIQ/manageiq-providers-ovirt/builds/179969403

**Comment by simaishi** [comment]
Closing the PR, the last hammer build was August 2020.

**Pull request closed without merging**
