### PR TITLE
v2v: Rephrase ISO driver label

### PR DESCRIPTION
**Pull request by matobet**
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1467858

### CODE REVIEW

**Comment by matobet** [comment]
@miq-bot assign @jelkosz

**Comment by matobet** [comment]
@miq-bot add_label fine/yes

**Comment by matobet** [comment]
@miq-bot assign @jhernand

**Comment by jelkosz** [comment]
@miq-bot assign @masayag

**Comment by jelkosz** [comment]
LGTM

**Comment by simaishi** [comment]
Fine backport (to manageiq repo) details:

```
$ git log -1
commit f9b9ad0ab6a9508f643fa9840ad43746bfac01c2
Author: Oved Ourfali <oourfali@redhat.com>
Date:   Thu Aug 10 15:07:55 2017 +0300

    Merge pull request #75 from matobet/master
    
    v2v: Rephrase ISO driver label
    (cherry picked from commit 14f889c1428098d235d50762f5a87457753bfd62)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1480586
ovpn-123-5:manageiq simaishi (fine) $ 

```

**Pull request merged**
