### PR TITLE
Bump ovirt-engine-sdk to 4.4.0

### PR DESCRIPTION
**Pull request by agrare**

### CODE REVIEW

**Comment by agrare** [comment]
cc @simaishi since this is a binary extension based gem

**Comment by djberg96** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1703055 woo!

**Comment by Fryguy** [comment]
Backported to `kasparov` in commit b6304292bc4d4499d483786960d2b3ba119d4a5c.

```text
commit b6304292bc4d4499d483786960d2b3ba119d4a5c
Author: Oleg Barenboim <chessbyte@gmail.com>
Date:   Fri Oct 30 08:50:43 2020 -0400

    Merge pull request #538 from agrare/bump_ovirt_engine_sdk
    
    Bump ovirt-engine-sdk to 4.4.0
    
    (cherry picked from commit c9a538c2320801e3af2cedb68c7b6e4181d8a20d)
```

**Comment by Fryguy** [comment]
@agrare A conflict occurred during the backport of this pull request to `jansa`.

If this pull request is based on another pull request that has not been marked for backport, add the appropriate labels to the other pull request. Otherwise, please create a new pull request direct to the `jansa` branch in order to resolve this.

Conflict details:

```diff
diff --cc manageiq-providers-ovirt.gemspec
index 16e7a48,8c011c4..0000000
--- a/manageiq-providers-ovirt.gemspec
+++ b/manageiq-providers-ovirt.gemspec
@@@ -1,20 -1,25 +1,24 @@@
 -# coding: utf-8
 -lib = File.expand_path('../lib', __FILE__)
 -$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
 -require 'manageiq/providers/ovirt/version'
 +$:.push File.expand_path("../lib", __FILE__)
  
 -Gem::Specification.new do |spec|
 -  spec.name          = "manageiq-providers-ovirt"
 -  spec.version       = ManageIQ::Providers::Ovirt::VERSION
 -  spec.authors       = ["ManageIQ Authors"]
 +require "manageiq/providers/ovirt/version"
  
 -  spec.summary       = "ManageIQ plugin for the oVirt provider."
 -  spec.description   = "ManageIQ plugin for the oVirt provider."
 -  spec.homepage      = "https://github.com/ManageIQ/manageiq-providers-ovirt"
 -  spec.license       = "Apache-2.0"
 +Gem::Specification.new do |s|
 +  s.name        = "manageiq-providers-ovirt"
 +  s.version     = ManageIQ::Providers::Ovirt::VERSION
 +  s.authors     = ["ManageIQ Developers"]
 +  s.homepage    = "https://github.com/ManageIQ/manageiq-providers-ovirt"
 +  s.summary     = "Ovirt Provider for ManageIQ"
 +  s.description = "Ovirt Provider for ManageIQ"
 +  s.licenses    = ["Apache-2.0"]
  
 -  spec.files         = `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
 -  spec.bindir        = "exe"
 -  spec.executables   = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }
 -  spec.require_paths = ["lib"]
 +  s.files = Dir["{app,config,lib}/**/*"]
  
++<<<<<<< HEAD
 +  s.add_runtime_dependency "ovirt-engine-sdk", "~>4.3.0"
++=======
+   spec.add_dependency "ovirt-engine-sdk", "~>4.4.0"
++>>>>>>> c9a538c... Merge pull request #538 from agrare/bump_ovirt_engine_sdk
  
 -  spec.add_development_dependency "manageiq-style"
 -  spec.add_development_dependency "simplecov"
 +  s.add_development_dependency "codeclimate-test-reporter", "~> 1.0.0"
 +  s.add_development_dependency "simplecov"
  end
```

**Comment by agrare** [comment]
@Fryguy https://github.com/ManageIQ/manageiq-providers-ovirt/pull/561

**Comment by Fryguy** [comment]
Backported to jansa via https://github.com/ManageIQ/manageiq-providers-ovirt/pull/561

**Comment by Fryguy** [comment]
`ivanchuk` backport details:

```
commit f0872e7f12e779f0f03626ac1ed41bc4db24e213 (HEAD -> ivanchuk, upstream/ivanchuk)
Author: Oleg Barenboim <chessbyte@gmail.com>
Date:   Fri Oct 30 08:50:43 2020 -0400

    Merge pull request #538 from agrare/bump_ovirt_engine_sdk

    Bump ovirt-engine-sdk to 4.4.0

    (cherry picked from commit c9a538c2320801e3af2cedb68c7b6e4181d8a20d)
```

**Pull request merged**
