### PR TITLE
Scope EmsFolder and ResourcePool queries by ems_id

### PR DESCRIPTION
**Pull request by agrare**
When searching for EmsFolders and ResourcePools by uid_ems scope by the
ems_id to prevent resources from being assigned to a folder in the wrong
EMS.

Fixes: https://github.com/ManageIQ/manageiq-providers-ovirt/issues/321

### CODE REVIEW

**Comment by simaishi** [comment]
@agrare The file doesn't exist in Gaprindashvili branch. Where does this change go in G branch?

**Comment by agrare** [comment]
@simaishi I'll make a PR to gaprindashvili, looks like there was a lot of refactoring in this area

**Comment by agrare** [comment]
@simaishi see https://github.com/ManageIQ/manageiq-providers-ovirt/pull/324

**Comment by simaishi** [comment]
Backported to Gaprindashvili via https://github.com/ManageIQ/manageiq-providers-ovirt/pull/324

**Pull request merged**
