### PR TITLE
Implement :reboot_guest for VM

### PR DESCRIPTION
**Pull request by matobet**
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1462803

### CODE REVIEW

**Comment by matobet** [comment]
@miq-bot assign @borod108

**Comment by matobet** [comment]
@jhernand @borod108 please review

**Comment by simaishi** [comment]
@matobet @oourfali can this PR be `fine/yes`?

**Comment by oourfali** [comment]
@miq-bot add_label fine/yes

**Comment by simaishi** [comment]
Fine backport (to manageiq repo) details:

```
$ git log -1
commit 597ada0ae7f153d19e8120ab60920bb4425a96f6
Author: Oved Ourfali <oourfali@redhat.com>
Date:   Mon Jun 26 13:33:52 2017 +0300

    Merge pull request #52 from matobet/master
    
    Implement :reboot_guest for VM
    (cherry picked from commit 5f46e1d4c1f035ad314f15c2f78868bf04b7ddad)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1478418
```

**Pull request merged**
