### PR TITLE
v2v: Make "install drivers" checkbox dynamic

### PR DESCRIPTION
**Pull request by matobet**
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1472843

### CODE REVIEW

**Comment by matobet** [comment]
Depends on https://github.com/ManageIQ/manageiq-content/pull/170

**Comment by matobet** [comment]
@miq-bot assign @masayag

**Comment by matobet** [comment]
@miq-bot add_label fine/yes

**Comment by masayag** [comment]
LGTM, waiting for the dependency to be merged first.

**Comment by jelkosz** [comment]
@simaishi could you please backport this?

**Comment by simaishi** [comment]
@jelkosz I can only backport 'blocker' PRs for the release we're currently working on right now. I'll backport once we start working on the next release.

**Comment by simaishi** [comment]
Fine backport (to manageiq repo) details:

```
$ git log -1
commit 2b879f88e39754d9e9a7878cd96fba36153114c4
Author: Greg McCullough <gmccullo@redhat.com>
Date:   Tue Sep 5 15:51:07 2017 -0400

    Merge pull request #76 from matobet/dynamic-checkbox
    
    v2v: Make "install drivers" checkbox dynamic
    (cherry picked from commit 0273a003fde7f1c52fa117ef1fe355303895a607)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1512955
```

**Pull request merged**
