### PR TITLE
oVirt network provider support routers, security groups and floating ips

### PR DESCRIPTION
**Pull request by AlonaKaplan**
oVirt network provider support routers, security groups and floating ips

### CODE REVIEW

**Comment by AlonaKaplan** [comment]
@borod108 please review

**Comment by borod108** [comment]
@AlonaKaplan do this changes effect any specs?
Also, are we sure it will work ok in queues? (When all of this happens? during refresh or creation?)

**Comment by AlonaKaplan** [comment]
1. @borod108 no specs effected.
2. Creation of  router/security groups/floating ips is done in a queue, so it should be ok.

**Comment by borod108** [comment]
1. @AlonaKaplan so this sounds suspicious :) If we do not have any specs for this perhaps we can at least add an issue to track adding them at some point. This kind of change seems to me like potentially risky.
2. Ok cool.

**Comment by AlonaKaplan** [comment]
@borod108  https://trello.com/c/w7UYk7UL/9-spec-for-manageiq-networks-subnets-ports-security-groups-floating-ips-routers

**Comment by AlonaKaplan** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit c49fe78fe718b9675c51a8910dde23178a1af4c7
Author: Oved Ourfali <oourfali@redhat.com>
Date:   Sun Nov 26 15:24:33 2017 +0200

    Merge pull request #144 from AlonaKaplan/master
    
    oVirt network provider support routers, security groups and floating ips
    (cherry picked from commit b063bedb162458e3b1f4cf39c35014290ec8039e)
```

**Pull request merged**
