### PR TITLE
[Changelog] Update for Hammer-5 release

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label hammer/yes

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit c53a15ca92cd687bf7781243f2bda88ef0b72579
Author: Adam Grare <agrare@redhat.com>
Date:   Wed Apr 17 15:06:30 2019 -0400

    Merge pull request #358 from JPrause/hammer5_cl
    
    [Changelog] Update for Hammer-5 release
    
    (cherry picked from commit 28efc995df38932abb742098946c46e9a1c102e2)
```

**Comment by simaishi** [comment]
@JPrause just noticed https://github.com/ManageIQ/manageiq-providers-ovirt/pull/315 isn't backported yet, so it won't be in `hammer-5` build.

**Pull request merged**
