### PR TITLE
Set tools_status based on presence of ovirt-guest-agent application

### PR DESCRIPTION
**Pull request by djberg96**
This PR updates the parser and collector to gather vm guest applications, and check for the presence of the ovirt-guest-agent. If present, the `tools_status` field is set to "installed", otherwise it is set to "not installed".

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1846624

Depends on https://github.com/ManageIQ/manageiq-providers-ovirt/pull/507

### CODE REVIEW

**Comment by agrare** [comment]
@djberg96 you'll need to re-record the vcr cassettes

**Comment by simaishi** [comment]
@djberg96  Can this be `ivanchuk/yes`?

**Comment by djberg96** [comment]
@agrare Any reason it can't?

**Comment by agrare** [comment]
Should be fine, no schema changes

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 5c3f0dafdd3ac7c7e67dc6c108d39da0b74dd92b
Author: Adam Grare <agrare@redhat.com>
Date:   Thu Jul 2 11:47:53 2020 -0400

    Merge pull request #505 from djberg96/tools_status_simple

    Set tools_status based on presence of ovirt-guest-agent application

    (cherry picked from commit b28f102816dcc2fe7daef07d1e5227aac048bf05)

    https://bugzilla.redhat.com/show_bug.cgi?id=1846624
```

**Pull request merged**
