### PR TITLE
Change "Empty" to "No Profile" in profile list

### PR DESCRIPTION
**Pull request by AlonaKaplan**

### CODE REVIEW

**Comment by AlonaKaplan** [comment]
@borod108 please review

**Comment by AlonaKaplan** [comment]
@borod108 load_allowed_vlan is test in infra_manager/provision_workflow_spec.rb.
Do you think the tests there are not enough?

**Comment by borod108** [comment]
@AlonaKaplan oh it is. For some reason when I looked I saw you made some changes and no tests broke, but now I see they did brake so its ok :) just need to fix them :)

**Comment by AlonaKaplan** [comment]
@borod108 please review

@miq-bot add_label gaprindashvili/yes

**Comment by AlonaKaplan** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 54c5522413bdb9e2bae2ee0e478a5074b0cee376
Author: Oved Ourfali <oourfali@redhat.com>
Date:   Sun Nov 26 10:31:14 2017 +0200

    Merge pull request #151 from AlonaKaplan/empty_profile
    
    Change "Empty" to "No Profile" in profile list
    (cherry picked from commit b7b57d1b968ca158a80652c6d020263148d2168e)
```

**Pull request merged**
