### PR TITLE
Handle console events

### PR DESCRIPTION
**Pull request by pkliczewski**
We need to make sure to handle console related events.

Bug-Url:
https://bugzilla.redhat.com/1518330

### CODE REVIEW

**Comment by pkliczewski** [comment]
This PR depends on https://github.com/ManageIQ/manageiq/pull/16624

**Comment by pkliczewski** [comment]
@oourfali do we want to fix it for v3 as well?

**Comment by pkliczewski** [comment]
@miq-bot assign @masayag

**Comment by pkliczewski** [comment]
@borod108 @jhernand please review

**Comment by pkliczewski** [comment]
@miq-bot add_labels gaprindashvili/yes

**Comment by pkliczewski** [comment]
@miq-bot add_labels fine/yes

**Comment by pkliczewski** [comment]
@miq-bot add_labels euwe/yes

**Comment by pkliczewski** [comment]
[Bug 1518330 - No event in timeline for the web console activity in RHV41](https://trello.com/c/L7sC9fz4/269-bug-1518330-no-event-in-timeline-for-the-web-console-activity-in-rhv41)

**Comment by pkliczewski** [comment]
@agrare please review

**Comment by pkliczewski** [comment]
@masayag @oourfali are we ok to merge it?

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 8ad7a60e5371da7c96e62b98942a34e1ed6a4ffb
Author: Oved Ourfali <oourfali@redhat.com>
Date:   Tue Dec 12 12:10:00 2017 +0200

    Merge pull request #173 from pkliczewski/master
    
    Handle console events
    (cherry picked from commit 69aed1fbd8ee3e7a9c9e89cb1c79aa2066b4ed64)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1525059
```

**Comment by simaishi** [comment]
@pkliczewski Not sure where the events go in Fine branch. Can you please create a separate PR?

**Comment by pkliczewski** [comment]
@simaishi I will create separate PR.

**Comment by pkliczewski** [comment]
[Bug 1525583 - No event in timeline for the web console activity in RHV41](https://trello.com/c/X1ZN7YrK/275-bug-1525583-no-event-in-timeline-for-the-web-console-activity-in-rhv41)

**Comment by pkliczewski** [comment]
@simaishi Here is fine backport: https://github.com/ManageIQ/manageiq/pull/16675

**Comment by simaishi** [comment]
Backported to Fine via https://github.com/ManageIQ/manageiq/pull/16675

**Pull request merged**
