### PR TITLE
oVirt gem update

### PR DESCRIPTION
**Pull request by pkliczewski**
We want to use the latest ovirt gem.

### CODE REVIEW

**Comment by pkliczewski** [comment]
@miq-bot assign @bdunne

**Comment by pkliczewski** [comment]
@masayag please review

**Comment by pkliczewski** [comment]
@miq-bot add_labels gaprindashvili/yes

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 8c1ac9025252233de3a090b8c1bad7096ee837de
Author: Brandon Dunne <brandondunne@hotmail.com>
Date:   Fri Jan 12 09:36:46 2018 -0500

    Merge pull request #194 from pkliczewski/master
    
    oVirt gem update
    (cherry picked from commit ad0baa2e1f8cfc3a4d37d47b160b486ad69fccd7)
```

**Pull request merged**
