### PR TITLE
Target new template when using api v4

### PR DESCRIPTION
**Pull request by pkliczewski**
Original implementation only provided such functionality for api v3.

### CODE REVIEW

**Comment by pkliczewski** [comment]
@masayag @borod108 Please review

**Comment by masayag** [comment]
Verified it also as part of 'publish vm' flow. The template's event is being caught instantly and triggers the template refresh.

**Comment by pkliczewski** [comment]
Are we OK to have it in?

**Comment by masayag** [comment]
Yes, the refresh error seems not related to this fix, and this fix is required for the 'publish vm' to work properly.

**Pull request merged**
