### PR TITLE
Profiles

### PR DESCRIPTION
**Pull request by AlonaKaplan**
Set 'Use template nics' as the default vnic profile option

depends on ManageIQ/manageiq#16504

### CODE REVIEW

**Comment by AlonaKaplan** [comment]
depends on https://github.com/ManageIQ/manageiq/pull/16504

**Comment by AlonaKaplan** [comment]
@masayag please review

**Comment by AlonaKaplan** [comment]
@masayag  the dependent PR  ManageIQ/manageiq#16504 was merged. Please merge this one as well. Thanks!

**Comment by AlonaKaplan** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit d9c5dede30e2c23c60cef121bd72489bae0f6f64
Author: Moti Asayag <masayag@redhat.com>
Date:   Thu Jan 11 10:00:31 2018 +0200

    Merge pull request #150 from AlonaKaplan/profiles
    
    Set '<Use template nics>' as the default vnic profile option
    (cherry picked from commit 94dc3477e941f15570f6b01126689f0747b0895e)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1533499
```

**Pull request merged**
