### PR TITLE
Discovery namespace change

### PR DESCRIPTION
**Pull request by gildub**
Reflect change in Discovery core introduced in https://github.com/ManageIQ/manageiq/pull/16994.

### CODE REVIEW

**Comment by gildub** [comment]
@d-m-u, @kbrock could you please review ASAP in order to walk away from the dual name space collusion?

**Comment by mwperina** [comment]
@masayag @borod108

**Comment by jrafanie** [comment]
👍

**Comment by gildub** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit b26d5d907b80020315b99cc4d5ac4efee8fa8115
Author: Boris Od <boris.od@gmail.com>
Date:   Thu Feb 15 11:44:59 2018 +0200

    Merge pull request #209 from gildub/discovery_core_change
    
    Discovery namespace change
    (cherry picked from commit 1213753f82fcc3f783b41bbc1363107d158d060a)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1552665
```

**Pull request merged**
