### PR TITLE
Unrecognized events during import from glance

### PR DESCRIPTION
**Pull request by pkliczewski**
There is set of events generated by importing images from glance which
are unrecognized by manageiq.

Fixes: https://bugzilla.redhat.com/1523257

### CODE REVIEW

**Comment by pkliczewski** [comment]
[Bug 1523257 - [RHV] Import image (as a template), from Glance (ext. provider) is unrecognized by CFME](https://trello.com/c/e41lbcbm/277-bug-1523257-rhv-import-image-as-a-template-from-glance-ext-provider-is-unrecognized-by-cfme)

**Comment by pkliczewski** [comment]
@miq-bot assign @masayag

**Comment by pkliczewski** [comment]
@borod108 please review

**Comment by pkliczewski** [comment]
@miq-bot add_labels bug, gaprindashvili/yes

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit a3389acf6fb5d9b375fc20e9a4b0beb2dd3e82fd
Author: Moti Asayag <masayag@redhat.com>
Date:   Tue Dec 19 12:36:38 2017 +0200

    Merge pull request #179 from pkliczewski/master
    
    Unrecognized events during import from glance
    (cherry picked from commit 587a72d1d8c948e51320557bd1fb22cf89fe8419)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1527568
```

**Pull request merged**
