### PR TITLE
Remodel to add networks by external providers

### PR DESCRIPTION
**Pull request by borod108**
Remodel the networking to add the vnic profiles related to networks that
are managed by external providers to the provisioning network dialog.

Related to: https://bugzilla.redhat.com/show_bug.cgi?id=1767787
Depends on: https://github.com/ManageIQ/manageiq/pull/19576

### CODE REVIEW

**Comment by simaishi** [comment]
@borod108 The description says this depends on https://github.com/ManageIQ/manageiq/pull/19576, but that PR isn't merged yet. Is the core PR no longer required?

**Comment by agrare** [comment]
@simaishi we decided not to use that change in core, https://github.com/ManageIQ/manageiq/pull/19576#issuecomment-561666254

I'll remove the depends on from the description

**Comment by simaishi** [comment]
@agrare Thank you.

@borod108 There are multiple conflicts backporting to ivanchuk. Please create a separate PR.

```
Changes to be committed:

	modified:   app/models/manageiq/providers/redhat/infra_manager.rb
	new file:   app/models/manageiq/providers/redhat/infra_manager/external_distributed_virtual_switch.rb
	modified:   app/models/manageiq/providers/redhat/inventory/collector/target_collection.rb
	modified:   app/models/manageiq/providers/redhat/inventory/persister/infra_manager.rb
	modified:   spec/models/manageiq/providers/redhat/infra_manager/refresh/ovirt_refresher_spec_common.rb
	new file:   spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher/target_response_yamls/external_network_providers_new.yml
	modified:   spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_template.yml
	modified:   spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_template_with_host.yml
	modified:   spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_after_full.yml
	modified:   spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_deleted_snapshot.yml
	modified:   spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_removal.yml
	modified:   spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/ovirt_sdk_refresh_graph_target_vm_with_host.yml
	modified:   spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_network_recording.yml
	new file:   spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_ovn_provider_1.yml

Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)

	both modified:   app/models/manageiq/providers/redhat/infra_manager/ovirt_services.rb
	both modified:   app/models/manageiq/providers/redhat/inventory/parser/infra_manager.rb
	both modified:   spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_graph_target_vm_spec.rb
	both modified:   spec/models/manageiq/providers/redhat/infra_manager/refresh/refresher_network_spec.rb
	deleted by us:   spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_reconfigure_with_no_restart_needed_recording.yml
	deleted by us:   spec/vcr_cassettes/manageiq/providers/redhat/infra_manager/refresh/refresher_reconfigure_with_restart_needed_recording.yml
```

**Comment by agrare** [comment]
Should be backported together with https://github.com/ManageIQ/manageiq-providers-ovirt/pull/457

**Comment by simaishi** [comment]
Backported to ivanchuk via https://github.com/ManageIQ/manageiq-providers-ovirt/pull/455

**Pull request merged**
