### PR TITLE
Fix travis network id nil

### PR DESCRIPTION
**Pull request by AlonaKaplan**

### CODE REVIEW

**Comment by AlonaKaplan** [comment]
@miq-bot add_labels gaprindashvili/yes

**Comment by AlonaKaplan** [comment]
@pkliczewski please review

**Comment by AlonaKaplan** [comment]
@borod108 please review

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit cf381288ed0cfc7b4f30952bd5c5ba7de681caed
Author: Boris Od <boris.od@gmail.com>
Date:   Thu Jun 7 08:39:41 2018 +0300

    Merge pull request #260 from AlonaKaplan/fix_travis_network_id_nil
    
    Fix travis network id nil
    (cherry picked from commit 78dc6000e37045f33de1dced62ea15893931812a)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1588042
```

**Pull request merged**
