### PR TITLE
Fix borken tests - update ovn cassette

### PR DESCRIPTION
**Pull request by AlonaKaplan**

### CODE REVIEW

**Comment by borod108** [comment]
@AlonaKaplan thank you! can you please fix the rubocops and we will merge it in.

**Comment by masayag** [comment]
@borod108 according to alkaplan, this PR should be backported to gaprindashvili in order to fix the broken specs.

**Comment by masayag** [comment]
@miq-bot add_label gaprindashvili/yes

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 8c51f26a3051673b85177327f69a4ecc9a3c744e
Author: Boris Od <boris.od@gmail.com>
Date:   Wed Feb 28 14:08:44 2018 +0200

    Merge pull request #218 from AlonaKaplan/specs2
    
    Fix borken tests - update ovn cassette
    (cherry picked from commit f5682512aad94feec4bfe1583827ac920d5f0f81)
```

**Comment by masayag** [comment]
@AlonaKaplan @borod108 the PR was backported to gaprindashvili, please verify it fixes the broken issues. I verified it locally.

**Pull request merged**
