### PR TITLE
Data-Driven create params and validate_credentials

### PR DESCRIPTION
**Pull request by agrare**
Add a data-driven-forms params_for_create allowing dynamic API driven
UI form building and add the standard validate_credentials API.

### CODE REVIEW

**Comment by agrare** [comment]
@borod108 we're working on allowing the API to drive what the UI forms required to add a provider requires.  Can you review this to check that I have what is required/optional and the types correct for `raw_connect`?
cc @skateman

**Comment by borod108** [comment]
@agrare this is a cool change :)
We do need to have RSA key pair creds as well.

**Comment by agrare** [comment]
Thanks @borod108, is this another endpoint or just another authentication type?

**Comment by borod108** [comment]
@agrare just an authentication type as far as I understand.

**Comment by borod108** [comment]
LGTM

**Pull request merged**
